services:
  
  sensor_fusion:
    image: sensor_fusion:v1
    build:
      context: .
      dockerfile: dockerfiles/all.dockerfile
    container_name: sensor_fusion
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - ROS_LOCALHOST_ONLY=1
      - ROS_DOMAIN_ID=5
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/udev:/run/udev:ro
      - /dev/rplidar:/dev/rplidar
    network_mode: host
    privileged: true


  camera_left:
    image: camera:left
    build:
      context: .
      dockerfile: dockerfiles/camera.dockerfile
    container_name: camera_left
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - ROS_LOCALHOST_ONLY=0
      - ROS_DOMAIN_ID=7
      - ID=0
      - OUTPUT="/camera_left"
      - NAME=camera_left
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/udev:/run/udev:ro
    networks:
      - ros2
    privileged: true

  camera_right:
    image: camera:right
    build:
      context: .
      dockerfile: dockerfiles/camera.dockerfile
    container_name: camera_right
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - ROS_LOCALHOST_ONLY=0
      - ROS_DOMAIN_ID=7
      - ID=1
      - OUTPUT="/camera_right"
      - NAME=camera_right
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/udev:/run/udev:ro
    networks:
      - ros2
    privileged: true
  
  preprocess_left:
    image: preprocess:left
    build:
      context: .
      dockerfile: dockerfiles/preprocess.dockerfile
    container_name: preprocess_left
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - ROS_LOCALHOST_ONLY=0
      - ROS_DOMAIN_ID=7
      - ID=0
      - OUTPUT="/camera_left"
      - NAME=camera_left
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/udev:/run/udev:ro
    networks:
      - ros2
    privileged: true
    

  # cameraPipeline:

  # lidarNode:

  # serverVisualization:


  # fuser:

networks:
  ros2:
    external: true
